name: Generate Pull Request

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write
  pull-requests: write
  
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create and switch to new branch
      run: |
        git checkout -b my-feature-branch
        git push origin my-feature-branch
        
    - name: Make changes
      run: |
        python main.py
        
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Update code"
        git push origin my-feature-branch
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update code"
        title: "My Pull Request"
        body: "Please review my changes"
        base: "main"
        head: "my-feature-branch"
